services:
    backend-app:
        build:
            context: './backend'
            dockerfile: Dockerfile
        image: 'find-my-way/backend'
        env_file:
            - ./backend/.env
        ports:
            - '8001:80'
        volumes:
            - './backend:/app'
    frontend-app:
        image: node:20-slim
        command: sh -c "npm install && npx vite --host"
        ports:
          - '5173:5173'
        volumes:
            - './frontend:/app'
        working_dir: /app
        stdin_open: true
        tty: true
    backend-db:
        image: 'mariadb:11'
        environment:
            MARIADB_DATABASE: 'laravel'
            MARIADB_USER: 'laravel'
            MARIADB_PASSWORD: 'laravel'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        ports: 
            - '9000:3306'
        volumes:
            - ./backend/db:/var/lib/mysql:Z
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
    fake-flights-api-1:
        build:
            context: './fake-flights-api'
            dockerfile: Dockerfile
        image: 'fake-flights-api'
        env_file:
            - ./fake-flights-api/.env.first
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8002:80'
        volumes:
            - './fake-flights-api:/app'
    fake-flights-api-1-db:
        image: 'mariadb:11'
        environment:
            MARIADB_DATABASE: 'laravel'
            MARIADB_USER: 'laravel'
            MARIADB_PASSWORD: 'laravel'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        ports: 
            - '9001:3306'
        volumes:
            - ./fake-flights-api/db:/var/lib/mysql:Z
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
    fake-flights-api-2:
        build:
            context: './fake-flights-api'
            dockerfile: Dockerfile
        image: 'fake-flights-api'
        env_file:
            - ./fake-flights-api/.env.second
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8003:80'
        volumes:
            - './fake-flights-api:/app'
    fake-flights-api-2-db:
        image: 'mariadb:11'
        environment:
            MARIADB_DATABASE: 'laravel'
            MARIADB_USER: 'laravel'
            MARIADB_PASSWORD: 'laravel'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        ports:
            - '9002:3306'
        volumes:
            - ./fake-flights-api/db2:/var/lib/mysql:Z
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s